# Generated by Django 4.0.3 on 2022-04-03 10:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_Post', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пост_Пользователя', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='Post.category')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id_response', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='Отклик')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость статьи')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_posts', to='Post.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Отклик_Пользователя', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
