# Generated by Django 4.0.3 on 2022-03-25 11:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_Post', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='Post.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пост_Пользователя', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id_response', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='Отклик')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость статьи')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_posts', to='Post.posts', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Отклик_Пользователя', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
